language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

env:
  - STOMP_PROVIDER=rabbitmq
  - STOMP_PROVIDER=apollo

before_script:
  - sh -c " if [ '$STOMP_PROVIDER' = 'apollo' ]; then
              wget http://mirror.catn.com/pub/apache/activemq/activemq-apollo/1.7/apache-apollo-1.7-unix-distro.tar.gz;
              tar xzf apache-apollo-1.7-unix-distro.tar.gz;
              ./apache-apollo-1.7/bin/apollo create apollo;
              ./apollo/bin/apollo-broker-service start;
              sleep 6;
            fi"
  - sh -c " if [ '$STOMP_PROVIDER' = 'rabbitmq' ]; then
              sudo rabbitmq-plugins enable rabbitmq_stomp;
              sudo service rabbitmq-server start;
            fi"
  - composer install --dev --prefer-source

script:
  - phpunit --coverage-text
  - phpunit -c phpunit-functional.xml.dist
